name: zwt_life_flutter_app
description: mylife

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  fluttertoast: ^2.2.6
  json_annotation: ^2.1.0
  flutter_redux: ^0.5.3
  device_info: ^0.3.0
  connectivity: ^0.3.2
  url_launcher: ^4.0.3
  flutter_markdown: ^0.2.0
  share: ^0.5.3
  flutter_spinkit: ^3.1.0
  flutter_webview_plugin: ^0.2.1+2
  sqflite: ^1.1.3
  pub_semver: ^1.4.2
  flutter_statusbar: ^0.0.1
  flutter_statusbarcolor: any
  flutter_svg: ^0.10.1
  photo_view: ^0.2.2
  flutter_slidable: ^0.4.9
  dio: ^2.1.0
  flutter_localizations:
    sdk: flutter
  event_bus:  ^1.0.1
  flutter_cache_manager: ^0.3.2
  path_provider: ^0.5.0+1
  scoped_model: ^1.0.1
  package_info: ^0.3.2
  fluwx: ^0.5.6
  flutter_swiper: ^1.1.4
  flutter_sound: ^1.3.7
  image_picker: ^0.4.12+1
  camera: ^0.4.2
  video_player: ^0.10.0+4
  flutter_easyrefresh: ^1.2.7
  flushbar: ^1.3.0
  pull_to_refresh: ^1.2.0
  battery: ^0.3.0+3
  flare_flutter: ^1.3.10
  extended_image: ^0.2.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  json_serializable: ^2.1.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
  - static/images/logo.png
  - static/images/welcome.png
  - static/images/default_img.png
  - static/images/login_background.png
  - static/images/voice.png
  - static/images/bookshelf1.png
  - static/images/bookshelf2.png
  - static/images/search.png
  - static/images/gender.png
  - static/images/read_bg.png
  - static/images/reader_battery.png
  - static/images/read_icon_brightness.png
  - static/images/read_icon_catalog.png
  - static/images/read_icon_font.png
  - static/images/read_icon_setting.png
  - static/images/fontheight2.png
  - static/images/fontheight3.png
  - static/images/fontheight4.png
  - static/images/searchblack.png
  - static/images/ic_find_in_page.png
  - static/images/booklist.png
  - static/images/sortlist.png
  - static/images/rankinglist.png


  fonts:
  - family: wxcIconFont
    fonts:
    - asset: static/font/iconfont.ttf